[general]
import = ["~/.config/alacritty/themes/onedark.toml"]

[env]
# Workaround to delude tmux
TERM = "screen-256color"

[window]
startup_mode = "Maximized"
padding = { x = 5, y = 5 }
decorations = "Buttonless"

[font]
size = 16
normal = { family = "RobotoMono Nerd Font", style = "Regular" }

[keyboard]
bindings = [
    { key = "Right", mods = "Alt", chars = "\u001BF" },
    { key = "Left", mods = "Alt", chars = "\u001BB" },
    { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
]
